name: CI/CD Pipeline for Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - uat
      - dev
      - feature-*
    paths:
      - 'frontend/**'
      - 'infrastructure/terraform/frontend/**'
  # pull_request:
  #   types: [closed]
  #   branches:
  #     - prod
  #     - uat
  #     - dev

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: frontend
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1